### ISSUE TITLE
Variable axis coordinates FAIL report

### ISSUE THREAD

**Issue by mightybart** [vv-monsalve/space-grotesk#10]
QA reports several FAILs, all related to axis coordinates not being a multiple of 100.

Light master = 300
Regular instance = **416**
Medium instance = **560**
Bold master = 700

There are slight shifts due to non-linear weight progression. Related to #9 

Any suggestions on how to deal with this issue?

**Comment by mightybart** [comment]
OK, should google this one first 🤦‍♂️  'stat' table

**Comment by mightybart** [comment]
Fixed using weightClass parameter. However, works only when using build.sh, does not work exporting directly via Glyphs. Didn't found a solution that would work for both cases.

Probably related to [/googlefonts/glyphsLib/issues/568](/googlefonts/glyphsLib/issues/568)

**Comment by vv-monsalve** [comment]
> Probably related to /googlefonts/glyphsLib/issues/568

Yes, it would be the best approach, so far. As you can see, there is a lot of debate on this subject, so I would go through this once we have the last (ready to production) source files.
