### ISSUE TITLE
Variable font repo structure

### ISSUE THREAD

**Issue by mightybart** [vv-monsalve/space-grotesk#11]
Are there any up to date guidelines for structuring variable font repository?

According to QA report, TTF folder should look something like this (otherwise there are FAIL reports for static TTF files not icluded in /ttf/static folder).

```
.
└── fonts
    ├── otf
    │   └── FontFamily-Regular.otf
    └── ttf
    │   ├── FontFamily[wght].ttf
    │   └── static
    │       └── FontFamily-Regular.ttf
    └── webfonts
        ├── FontFamily[wght].woff2
        └── FontFamily-Regular.woff2
```

Also not sure about varibale webfont placement.

**Comment by vv-monsalve** [comment]
No, there isn't a particular specification for it. I saw your structure placing the variable into the ttf folder and there the static folder and I found it interesting.
Nevertheless, there is a new version of Fontbakery (0.7.25) that fixed that fail, please update it.

**Comment by mightybart** [comment]
I kinda like the static folder inside the "ttf" and "woff2" folders, I think it's definitely better to keep variable and static files separate. So if there is nothing wrong with that I would use this system:

```
.
└── fonts
    ├── otf
    │   ├── FontFamily-Regular.otf
    │   └── FontFamily-Bold.otf
    └── ttf
    │   ├── FontFamily[wght].ttf
    │   └── static
    │       ├── FontFamily-Regular.ttf
    │       └── FontFamily-Bold.ttf
    └── woff2
        ├── FontFamily[wght].woff2
        └── static
            ├── FontFamily-Regular.woff2
            └── FontFamily-Bold.woff2
```

Or a flat structure like this might also work:

```
.
└── fonts
    ├── otf
    │   ├── FontFamily-Regular.otf
    │   └── FontFamily-Bold.otf
    └── ttf-static
    │   ├── FontFamily-Regular.ttf
    │   └── FontFamily-Bold.ttf
    └── ttf-variable
    │   └── FontFamily[wght].ttf
    └── woff2-static
    │   ├── FontFamily-Regular.woff2
    │   └── FontFamily-Bold.woff2
    └── woff2-variable
        └── FontFamily[wght].woff2
```

**Comment by vv-monsalve** [comment]
I would follow the first approach. I found it more clear

**Comment by mightybart** [comment]
I agree. Already using that system, so I'm closing this issue.
