### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/space-grotesk#5]
GF Rules for [Vertical Metrics](https://github.com/googlefonts/gf-docs/tree/master/VerticalMetrics) establish every font in a family must share the same vertical metric values. Nevertheless, Space Mono, which is the family already published, has much taller vertical metrics than common UI fonts.

![Space-Grotesk_Vertical-Metrics01](https://user-images.githubusercontent.com/48698976/81101561-f3ef2080-8ed3-11ea-85e7-8f2fed9625fa.gif)

In this case, should we match:
A) Space Mono with Space Grotesque, 
B) Space Grotesk to user expectations of UI fonts,
or C) change both to match system fonts?

The current values are (on the left column, Space Mono):
![Screen Shot 2020-05-04 at 21 12 14](https://user-images.githubusercontent.com/48698976/81031341-92866d80-8e51-11ea-8199-2dd9675e5f09.png)

--

On option B). considering the numbers on both fonts, following the spec and ensuring avoid clipping in Windows across the Family, this would be the suggested values:

typoAscender, hheaAscender: 950
winAscent: 1120
TypoDescender, hheaDescender: -330
winDescent: 361
typoLineGap and hheaLineGap: 0

Comparison of the resulting line hight with most widely-used fonts on UI design

![Space-Grotesk_Vertical-Metrics](https://user-images.githubusercontent.com/48698976/81103313-78db3980-8ed6-11ea-8f91-2fed01b1f4c0.gif)

**Comment by davelab6** [comment]
@vv-monsalve does space mono pass the current FB checks for v metrics?

**Comment by vv-monsalve** [comment]
I've run now the FB checks and there is no Fail reported on this.

**Comment by mightybart** [comment]
Option B seems like the best solution. Matching Space Mono and Space Grotesk would be even better, but that would require changing Space Mono metrics, and that would probably break things for many people already using it.

**Comment by mightybart** [comment]
Currently using:

typoAscender, hheaAscender: 960 (covers Å)
typoDescender, hheaDescender: -320 (covers Ģ)
typoLineGap and hheaLineGap: 0
= line height 128%

winAscent: 1052 (covers Ẵ – highest point is 1034, however minimal value according to QA is 1052, lower value reports FAIL)
winDescent: 314 (covers Ģ – lowest point)

When using typoAscender 950 & typoDescender -330 the baseline was placed a little bit too high in the bounding box > changed to 960/-320

**Comment by vv-monsalve** [comment]
No, winAscetn and Descent must be the same as the family's tallest/deepest _yMin_ and _yMax_ bbox values, to avoid clipping. Please have in mind the specification for [Vertical Metrics](https://github.com/googlefonts/gf-docs/tree/master/VerticalMetrics#4-win-ascent-and-win-descent-values-must-be-the-same-as-the-familys-tallestdeepest-ymin-and-ymax-bbox-values)

These are the yMin and yMax values on my local copy of the file. So the winDescent should be at least -351.
![Screen Shot 2020-05-15 at 10 55 49](https://user-images.githubusercontent.com/48698976/82070847-ec313800-969a-11ea-9105-783376620f81.png)



I'll pull your latest files to inspect that on the updated sources.

**Comment by mightybart** [comment]
Yes that is probably the previous version, in v2 it should be Gcommaaccent -312

**Comment by mightybart** [comment]
Latest values (a little higher than currently needed, but ready for future Black master):

typoAscender, hheaAscender = 960
typoDescender, hheaDescender = -340
typoLineGap, hheaLineGap = 0
winAscent = 1150
winDescent = 340

**Comment by vv-monsalve** [comment]
I would look at this in detail when running the test. At this moment what I would say is, as long as it has the Use of Typo Metrics enabled and the values are the same for all the masters I think it would be ok.

**Comment by mightybart** [comment]
Final VM > floriankarsten#21

**Comment by vv-monsalve** [comment]
Solved in https://github.com/floriankarsten/space-grotesk/issues/21#issuecomment-705255303
Closing this here
