### ISSUE TITLE
Information files & copyright

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/space-grotesk#6]
Please give a new revision to all of the information pieces having these requirements in mind.

**AUTHORS.txt and CONTRIBUTORS.txt**
Please be sure to include all the necessary info here. CONTRIBUTORS is the official list of people who have contributed to the project, while the AUTHORS file lists the copyright holders. 
For cases of designs based on previous projects, have a look at [this](https://github.com/google/fonts/issues/2161) for reference.

**Copyright strings**
For COPYRIGHT_NOTICE (nameID 0) only ASCII characters are required because that string should be the same in CFF fonts, which also have this requirement in the OpenType spec; thus the copyright symbol must be removed.
Copyright notices should also match a canonical pattern in fonts: “Copyright 2019 The Familyname Project Authors (git URL)”
For this project, the copyright in Font Info should be: Copyright 2019 The Space Grotesk Project Authors (https://github.com/floriankarsten/space-grotesk)

**OFL.txt**
The first line in OFL.txt file should be the font copyright as it is in Font Info: Copyright 2019 The Space Grotesk Project Authors (https://github.com/floriankarsten/space-grotesk)

**DESCRIPTION.en_us.html**
The snippet of HTML in the DESCRIPTION.en_us.html file is added to the font family webpage on the Google Fonts website.

This file must include:

- A hypertext link to the repository where the font project files are made available (designer’s GitHub repository)
- It should have more than 200 characters and less than 1000.
- All links in it must be properly working.
- Families with variable should always mention that in their descriptions.
- Name table strings must not contain the line ‘Reserved Font Name’ (RFNs on Github makes forking and modifying the fonts be infringing; it also means web font users must rename the fonts if they subset them, which is not the idea on open source projects.

**Comment by vv-monsalve** [comment]
**Readme.md**
Please, remember to update also the readme.md file with the last changes.

About more documentation images and information  (e.g., for the microsite), [Space Mono article](https://medium.com/google-design/introducing-space-mono-a-new-monospaced-typeface-by-colophon-foundry-for-google-fonts-84367eac6dfb) could be handy as a reference.

**Comment by mightybart** [comment]
AUTHORS, CONTRIBUTORS, OFL: fixed
Description, Readme: update still needed

**Comment by vv-monsalve** [comment]
The Description file is still pending, and it is required to make the PR to Google Fonts.  
I added a dummy file into the repository. You would need to edit it following the former requirements, remembering Space Mono is mentioned as the origin of the project, see this as reference:
[Previous authors credit](https://github.com/google/fonts/issues/2161)
[Sora Description file](https://github.com/vv-monsalve/sora-font/blob/QA-sora/DESCRIPTION.en_us.html)

**Comment by vv-monsalve** [comment]
> The Description file is still pending, and it is required to make the PR to Google Fonts.
> I added a dummy file into the repository. You would need to edit it following the former requirements, remembering Space Mono is mentioned as the origin of the project, see this as reference:
> [Previous authors credit](https://github.com/google/fonts/issues/2161)
> [Sora Description file](https://github.com/vv-monsalve/sora-font/blob/QA-sora/DESCRIPTION.en_us.html)

@mightybart Please adjust this file to what was suggested. This one is the priority before the launching.
Please also add a Fontlog file with a lists changes to each release into the repository.

**Comment by vv-monsalve** [comment]
Sorry, my bad on the Authors file. Nevertheless, I think Colophon Foundry should be included in the Contributors file.
@davelab6 what would you say?

**Comment by mightybart** [comment]
Both files updated.

✅ DESCRIPTION.en_us.html does contain information about the source fonts and original authors (description also indetical with README.md)
✅ Colophon Foundry included in CONTRIBUTORS.txt

**Comment by vv-monsalve** [comment]
> ✅ DESCRIPTION.en_us.html does contain information about the source fonts and original authors (description also indetical with README.md)
Yes, I noticed that. The Pull Request was already done and merged with the previous information (without the added links here).

> ✅ Colophon Foundry included in CONTRIBUTORS.txt
Thanks!
