### ISSUE TITLE
Kerning and OT features

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/space-grotesk#7]
Please, check at least the most [common kerns](https://github.com/googlefonts/fontbakery/issues/2739) are present.
This could be a helpful tool to generate [kerning pairs](https://justanotherfoundry.com/generator) for testing.

**Ligatures, kerning and carets**
Fonts with ligatures should have kerning on the corresponding non-ligated sequences for text where ligatures aren’t used (eg [https://github.com/impallari/Raleway/issues/14](https://github.com/impallari/Raleway/issues/14))
At the same time, all ligatures in a font must have corresponding caret (text cursor) positions defined in the GDEF table, otherwise, users may experience issues with caret rendering.

**OT features**
Please ensure the OT covers all the existing glyphs and features on the font. (e.g. dnom/numr, liga, frac, among others)

**Comment by mightybart** [comment]
Fixed
